// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Xmas tree

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void Tree_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Image_Tree;
// CUSTOM VARIABLES
lv_obj_t *uic_Image_Tree;

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t *ui_imgset_frame_[48] = {&ui_img_tree_frame_00_png, &ui_img_tree_frame_01_png, &ui_img_tree_frame_02_png, &ui_img_tree_frame_03_png, &ui_img_tree_frame_04_png, &ui_img_tree_frame_05_png, &ui_img_tree_frame_06_png, &ui_img_tree_frame_07_png, &ui_img_tree_frame_08_png, &ui_img_tree_frame_09_png, &ui_img_tree_frame_10_png, &ui_img_tree_frame_11_png, &ui_img_tree_frame_12_png, &ui_img_tree_frame_13_png, &ui_img_tree_frame_14_png, &ui_img_tree_frame_15_png, &ui_img_tree_frame_16_png, &ui_img_tree_frame_17_png, &ui_img_tree_frame_18_png, &ui_img_tree_frame_19_png, &ui_img_tree_frame_20_png, &ui_img_tree_frame_21_png, &ui_img_tree_frame_22_png, &ui_img_tree_frame_23_png, &ui_img_tree_frame_24_png, &ui_img_tree_frame_25_png, &ui_img_tree_frame_26_png, &ui_img_tree_frame_27_png, &ui_img_tree_frame_28_png, &ui_img_tree_frame_29_png, &ui_img_tree_frame_30_png, &ui_img_tree_frame_31_png, &ui_img_tree_frame_32_png, &ui_img_tree_frame_33_png, &ui_img_tree_frame_34_png, &ui_img_tree_frame_35_png, &ui_img_tree_frame_36_png, &ui_img_tree_frame_37_png, &ui_img_tree_frame_38_png, &ui_img_tree_frame_39_png, &ui_img_tree_frame_40_png, &ui_img_tree_frame_41_png, &ui_img_tree_frame_42_png, &ui_img_tree_frame_43_png, &ui_img_tree_frame_44_png, &ui_img_tree_frame_45_png, &ui_img_tree_frame_46_png, &ui_img_tree_frame_47_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void Tree_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->imgset = (lv_img_dsc_t **)ui_imgset_frame_;
PropertyAnimation_0_user_data->imgset_size = sizeof(ui_imgset_frame_)/(sizeof(lv_img_dsc_t*));
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_frame );
lv_anim_set_values(&PropertyAnimation_0, 0, 47 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_frame );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
