// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Xmas tree

#ifndef _XMAS_TREE_UI_H
#define _XMAS_TREE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void Tree_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Image_Tree;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Image_Tree;

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_tree_frame_00_png);   // assets/Tree/frame_00.png
LV_IMG_DECLARE( ui_img_tree_frame_01_png);   // assets/Tree/frame_01.png
LV_IMG_DECLARE( ui_img_tree_frame_02_png);   // assets/Tree/frame_02.png
LV_IMG_DECLARE( ui_img_tree_frame_03_png);   // assets/Tree/frame_03.png
LV_IMG_DECLARE( ui_img_tree_frame_04_png);   // assets/Tree/frame_04.png
LV_IMG_DECLARE( ui_img_tree_frame_05_png);   // assets/Tree/frame_05.png
LV_IMG_DECLARE( ui_img_tree_frame_06_png);   // assets/Tree/frame_06.png
LV_IMG_DECLARE( ui_img_tree_frame_07_png);   // assets/Tree/frame_07.png
LV_IMG_DECLARE( ui_img_tree_frame_08_png);   // assets/Tree/frame_08.png
LV_IMG_DECLARE( ui_img_tree_frame_09_png);   // assets/Tree/frame_09.png
LV_IMG_DECLARE( ui_img_tree_frame_10_png);   // assets/Tree/frame_10.png
LV_IMG_DECLARE( ui_img_tree_frame_11_png);   // assets/Tree/frame_11.png
LV_IMG_DECLARE( ui_img_tree_frame_12_png);   // assets/Tree/frame_12.png
LV_IMG_DECLARE( ui_img_tree_frame_13_png);   // assets/Tree/frame_13.png
LV_IMG_DECLARE( ui_img_tree_frame_14_png);   // assets/Tree/frame_14.png
LV_IMG_DECLARE( ui_img_tree_frame_15_png);   // assets/Tree/frame_15.png
LV_IMG_DECLARE( ui_img_tree_frame_16_png);   // assets/Tree/frame_16.png
LV_IMG_DECLARE( ui_img_tree_frame_17_png);   // assets/Tree/frame_17.png
LV_IMG_DECLARE( ui_img_tree_frame_18_png);   // assets/Tree/frame_18.png
LV_IMG_DECLARE( ui_img_tree_frame_19_png);   // assets/Tree/frame_19.png
LV_IMG_DECLARE( ui_img_tree_frame_20_png);   // assets/Tree/frame_20.png
LV_IMG_DECLARE( ui_img_tree_frame_21_png);   // assets/Tree/frame_21.png
LV_IMG_DECLARE( ui_img_tree_frame_22_png);   // assets/Tree/frame_22.png
LV_IMG_DECLARE( ui_img_tree_frame_23_png);   // assets/Tree/frame_23.png
LV_IMG_DECLARE( ui_img_tree_frame_24_png);   // assets/Tree/frame_24.png
LV_IMG_DECLARE( ui_img_tree_frame_25_png);   // assets/Tree/frame_25.png
LV_IMG_DECLARE( ui_img_tree_frame_26_png);   // assets/Tree/frame_26.png
LV_IMG_DECLARE( ui_img_tree_frame_27_png);   // assets/Tree/frame_27.png
LV_IMG_DECLARE( ui_img_tree_frame_28_png);   // assets/Tree/frame_28.png
LV_IMG_DECLARE( ui_img_tree_frame_29_png);   // assets/Tree/frame_29.png
LV_IMG_DECLARE( ui_img_tree_frame_30_png);   // assets/Tree/frame_30.png
LV_IMG_DECLARE( ui_img_tree_frame_31_png);   // assets/Tree/frame_31.png
LV_IMG_DECLARE( ui_img_tree_frame_32_png);   // assets/Tree/frame_32.png
LV_IMG_DECLARE( ui_img_tree_frame_33_png);   // assets/Tree/frame_33.png
LV_IMG_DECLARE( ui_img_tree_frame_34_png);   // assets/Tree/frame_34.png
LV_IMG_DECLARE( ui_img_tree_frame_35_png);   // assets/Tree/frame_35.png
LV_IMG_DECLARE( ui_img_tree_frame_36_png);   // assets/Tree/frame_36.png
LV_IMG_DECLARE( ui_img_tree_frame_37_png);   // assets/Tree/frame_37.png
LV_IMG_DECLARE( ui_img_tree_frame_38_png);   // assets/Tree/frame_38.png
LV_IMG_DECLARE( ui_img_tree_frame_39_png);   // assets/Tree/frame_39.png
LV_IMG_DECLARE( ui_img_tree_frame_40_png);   // assets/Tree/frame_40.png
LV_IMG_DECLARE( ui_img_tree_frame_41_png);   // assets/Tree/frame_41.png
LV_IMG_DECLARE( ui_img_tree_frame_42_png);   // assets/Tree/frame_42.png
LV_IMG_DECLARE( ui_img_tree_frame_43_png);   // assets/Tree/frame_43.png
LV_IMG_DECLARE( ui_img_tree_frame_44_png);   // assets/Tree/frame_44.png
LV_IMG_DECLARE( ui_img_tree_frame_45_png);   // assets/Tree/frame_45.png
LV_IMG_DECLARE( ui_img_tree_frame_46_png);   // assets/Tree/frame_46.png
LV_IMG_DECLARE( ui_img_tree_frame_47_png);   // assets/Tree/frame_47.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
